#!/usr/bin/env python3
"""One-time ClickUp Doc → local HTML export.

Reads CLICKUP_API_KEY (or CLICKUP_API_TOKEN) from the environment.
Writes the Doc root to index.html and nested pages as slug/index.html.
"""

from __future__ import annotations

import argparse
import hashlib
import html as html_lib
import json
import os
import re
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

import markdown

WORKSPACE_ID = "10621157"
DOC_ID = "a4475-167"
API_BASE = "https://api.clickup.com/api/v3"

CLICKUP_HOST_RE = re.compile(
    r"^https?://(?:app\.clickup\.com|attachments(?:\d+)?\.clickup\.com|"
    r"t-\d+\.clickup\.com|clickup\.com)/",
    re.I,
)
IMG_MD_RE = re.compile(r"!\[([^\]]*)\]\(([^)\s]+)(?:\s+\"[^\"]*\")?\)")
IMG_HTML_RE = re.compile(r'(<img\b[^>]*\bsrc=["\'])([^"\']+)(["\'])', re.I)
HREF_RE = re.compile(r'(<a\b[^>]*\bhref=["\'])([^"\']+)(["\'])', re.I)
MD_LINK_RE = re.compile(r"(?<!!)\[([^\]]+)\]\(([^)\s]+)(?:\s+\"[^\"]*\")?\)")

# Root-relative paths the exporter must never overwrite.
PROTECTED = {
    "index.html",
    "sleeper-week17-rosters.html",
    "export_clickup.py",
    "requirements.txt",
    "site.css",
    "site.js",
    "nav.json",
    ".gitignore",
}

SITE_NAV = (
    ("2026 Season", "this-season/"),
    ("Past Seasons", "past-seasons/"),
    ("Rules", "rules/"),
)

# Top-level ClickUp pages are re-homed here; everything else nests under its parent.
TOP_LEVEL_PATHS = {
    "league-info-rules": "rules",
    "2025-2026-season": "past-seasons/2025-2026-season",
    "past-seasons": "past-seasons",
}

# Overrides for page names that read poorly in ClickUp.
PAGE_TITLES = {
    "past-seasons/2021-2022-season/": "2021 - 2022 Season",
}

# Children pulled to the top of their nav section, in the order listed.
NAV_FIRST = {
    "past-seasons/": ("past-seasons/hall-of-champions/",),
    "rules/": ("index.html", "2026-keepers/"),
}

SITE_CSS = """\
/* Fantasy Fucks - site-wide styles. Generated by export_clickup.py. */

:root,
[data-theme="light"] {
  color-scheme: light;
  --bg: #eeebe4;
  --bg-elev: #ffffff;
  --bg-elev-2: #f4f2ec;
  --border: #ddd9d0;
  --text: #111111;
  --text-dim: #4a4a4a;
  --text-faint: #7a7a7a;
  --accent: #c6f04d;
  --accent-ink: #111111;
  --accent-text: #3d6a08;
  --gold: #c9a227;
  --silver: #6b6b6b;
  --bronze: #8a4e1a;
  --qb: #c41218;
  --rb: #1a6b4a;
  --wr: #1a4f8a;
  --te: #9a4a12;
  --k: #5a2a7a;
  --def: #4a4a4a;
  --slutler: #c41218;
  --ir: #c41218;
  --held: #1a6b4a;
  --miss: #c41218;
  --early: #5a2a7a;
  --other: #9a4a12;
  --chrome: #111111;
  --chrome-text: #f5f5f5;
  --chrome-dim: #a3a3a3;
  --controls-bg: #eeebe4;
  --row-border: rgba(17,17,17,.1);
  --avatar-bg: #ddd9d0;
  --chip-hover-border: #c4c0b6;
  --label-bg: rgba(17,17,17,.04);
  --hit-bg: rgba(198,240,77,.28);
  --tint: 22%;
  --tint-soft: 14%;
  --radius: 16px;
  --radius-pill: 999px;
  --sidebar-w: 268px;
  --topbar-h: 56px;
  --scrim: rgba(17,17,17,.45);
  --shadow: 10px 0 28px rgba(17,17,17,.18);
  --font-sans: "Helvetica Neue", Helvetica, Arial, sans-serif;
  --font-display: "Helvetica Neue", Helvetica, Arial, sans-serif;
  --font-serif: Georgia, "Times New Roman", serif;
}

[data-theme="dark"] {
  color-scheme: dark;
  --bg: #141414;
  --bg-elev: #1c1c1c;
  --bg-elev-2: #262626;
  --border: #333333;
  --text: #f3f3f3;
  --text-dim: #b5b5b5;
  --text-faint: #888888;
  --accent: #c6f04d;
  --accent-ink: #111111;
  --accent-text: #c6f04d;
  --gold: #d4a017;
  --silver: #c3b8a6;
  --bronze: #c4843a;
  --qb: #e06b6b;
  --rb: #6bb89a;
  --wr: #7aa8d4;
  --te: #d4924a;
  --k: #b089c9;
  --def: #8a8074;
  --slutler: #e06b6b;
  --ir: #e06b6b;
  --held: #6bb89a;
  --miss: #e06b6b;
  --early: #b089c9;
  --other: #d4924a;
  --chrome: #0d0d0d;
  --chrome-text: #f5f5f5;
  --chrome-dim: #9a9a9a;
  --controls-bg: #141414;
  --row-border: rgba(255,255,255,.08);
  --avatar-bg: #333333;
  --chip-hover-border: #4a4a4a;
  --label-bg: rgba(255,255,255,.06);
  --hit-bg: rgba(198,240,77,.14);
  --tint: 22%;
  --tint-soft: 14%;
  --scrim: rgba(0,0,0,.7);
  --shadow: 10px 0 28px rgba(0,0,0,.5);
}

* { box-sizing: border-box; }
html, body { margin: 0; padding: 0; }
body {
  background: var(--bg);
  color: var(--text);
  font: 15px/1.5 var(--font-sans);
  -webkit-font-smoothing: antialiased;
}
::selection { background: var(--accent); color: var(--accent-ink); }
a { color: var(--text); text-decoration-color: var(--accent); text-underline-offset: 3px; text-decoration-thickness: 2px; }
a:hover { color: var(--text); background: color-mix(in srgb, var(--accent) 55%, transparent); }
img { max-width: 100%; height: auto; }

.skip-link {
  position: absolute;
  left: -9999px;
  top: 0;
  z-index: 100;
  padding: 10px 14px;
  background: var(--bg-elev);
  border: 1px solid var(--border);
  border-radius: var(--radius-pill);
}
.skip-link:focus { left: 12px; top: 12px; }

/* shell */
.shell { display: flex; align-items: flex-start; min-height: 100vh; }
.content { flex: 1; min-width: 0; }

/* sidebar */
.sidebar {
  position: sticky;
  top: 0;
  z-index: 40;
  flex: 0 0 var(--sidebar-w);
  width: var(--sidebar-w);
  height: 100vh;
  display: flex;
  flex-direction: column;
  background: var(--chrome);
  color: var(--chrome-text);
  border-right: 0;
  transition: margin-left .18s ease;
}
[data-nav="collapsed"] .sidebar { margin-left: calc(var(--sidebar-w) * -1); }

.sidebar-top {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 10px;
  padding: 18px 14px 16px 16px;
  border-bottom: 0;
}
.brand {
  display: flex;
  align-items: center;
  gap: 10px;
  color: var(--chrome-text);
  text-decoration: none;
  min-width: 0;
}
.brand:hover { background: transparent; color: var(--chrome-text); }
.brand-mark {
  flex: 0 0 auto;
  width: 12px;
  height: 12px;
  border-radius: 50%;
  background: var(--accent);
  color: transparent;
  font-size: 0;
  overflow: hidden;
}
.brand-name {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  font-family: var(--font-display);
  font-size: 15px;
  font-weight: 800;
  letter-spacing: .04em;
  line-height: 1;
  text-transform: uppercase;
}

.icon-btn {
  display: grid;
  place-items: center;
  width: 34px;
  height: 34px;
  flex: 0 0 auto;
  background: transparent;
  border: 1px solid transparent;
  color: var(--chrome-dim);
  font-size: 16px;
  line-height: 1;
  cursor: pointer;
  font-family: inherit;
  border-radius: var(--radius-pill);
}
.icon-btn:hover { color: var(--chrome-text); background: #2a2a2a; }
.sidebar-dismiss { display: none; }

.sidebar-nav {
  flex: 1;
  overflow-y: auto;
  overscroll-behavior: contain;
  padding: 8px 10px 20px;
}
.nav-list { list-style: none; margin: 0; padding: 0; }
.nav-sub {
  margin: 2px 0 8px 10px;
  padding-left: 10px;
  border-left: 1px solid #2e2e2e;
  display: none;
}
.nav-node[data-open="true"] > .nav-sub { display: block; }
.nav-row { display: flex; align-items: stretch; gap: 0; }
.nav-link {
  flex: 1;
  min-width: 0;
  display: block;
  padding: 7px 12px;
  color: var(--chrome-dim);
  text-decoration: none;
  font-size: 13.5px;
  font-weight: 600;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  border-radius: var(--radius-pill);
}
.nav-sub .nav-link { font-size: 13px; font-weight: 500; color: #8a8a8a; }
.nav-link:hover { color: var(--chrome-text); background: #2a2a2a; }
.nav-node.is-branch > .nav-row > .nav-link:not([aria-current="page"]) { color: var(--chrome-text); }
.nav-link[aria-current="page"] {
  color: var(--accent-ink);
  background: var(--accent);
  font-weight: 700;
}
.nav-link[aria-current="page"]:hover { color: var(--accent-ink); background: var(--accent); }
.nav-caret {
  flex: 0 0 auto;
  width: 32px;
  border: 0;
  background: transparent;
  color: var(--chrome-dim);
  cursor: pointer;
  font-size: 18px;
  line-height: 1;
  font-family: inherit;
  border-radius: var(--radius-pill);
}
.nav-caret:hover { color: var(--chrome-text); }
.nav-caret::before { content: "\\25B8"; display: inline-block; transition: transform .15s ease; }
.nav-node[data-open="true"] > .nav-row > .nav-caret::before { transform: rotate(90deg); }

.sidebar-bottom {
  padding: 10px 12px 14px;
  border-top: 1px solid #2e2e2e;
}
.theme-btn {
  width: 100%;
  padding: 8px 12px;
  background: transparent;
  border: 1px solid #3a3a3a;
  color: var(--chrome-text);
  font: 700 12px/1 var(--font-sans);
  cursor: pointer;
  text-transform: none;
  letter-spacing: 0;
  border-radius: var(--radius-pill);
}
.theme-btn:hover { color: var(--accent-ink); background: var(--accent); border-color: var(--accent); }

/* topbar */
.topbar {
  position: sticky;
  top: 0;
  z-index: 30;
  height: var(--topbar-h);
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 0 22px;
  background: var(--chrome);
  border-bottom: 0;
}
.topbar .icon-btn { color: var(--chrome-dim); }
.topbar .icon-btn:hover { color: var(--chrome-text); background: #2a2a2a; }
.topbar-title {
  min-width: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  font-family: var(--font-display);
  font-size: 13px;
  font-weight: 800;
  letter-spacing: .06em;
  text-transform: uppercase;
  color: var(--chrome-text);
}
.topbar .spacer { flex: 1; }

.scrim {
  display: none;
  position: fixed;
  inset: 0;
  z-index: 35;
  background: var(--scrim);
}

/* page body */
main.page {
  max-width: 740px;
  margin: 0 auto;
  padding: 36px 32px 10px;
}
.crumbs {
  margin: 0 0 10px;
  color: var(--text-faint);
  font-size: 12px;
  font-weight: 700;
  letter-spacing: .04em;
  text-transform: uppercase;
  font-family: var(--font-sans);
}
.crumbs a { color: var(--text-faint); text-decoration: none; background: none; }
.crumbs a:hover { color: var(--text); background: none; }
.meta {
  margin: 0 0 28px;
  color: var(--text-faint);
  font-size: 13px;
  font-family: var(--font-sans);
}
h1 {
  margin: 0 0 10px;
  font-family: var(--font-display);
  font-size: 42px;
  line-height: 1.05;
  letter-spacing: -.03em;
  font-weight: 800;
  text-transform: none;
}
.subtitle {
  margin: 0 0 8px;
  color: var(--text-dim);
  font-family: var(--font-serif);
  font-style: italic;
  font-size: 20px;
}

.prose { font-size: 18px; font-family: var(--font-serif); line-height: 1.6; }
.prose :first-child { margin-top: 0; }
.prose h1, .prose h2, .prose h3 {
  font-family: var(--font-display);
  line-height: 1.15;
  letter-spacing: -.02em;
  margin: 1.5em 0 .4em;
  text-transform: none;
  font-weight: 800;
}
.prose h1 { font-size: 28px; }
.prose h2 { font-size: 22px; }
.prose h3 {
  font-size: 16px;
  font-style: normal;
  letter-spacing: 0;
  font-family: var(--font-sans);
}
.prose img { border-radius: var(--radius); }
.prose hr {
  border: 0;
  border-top: 1px solid var(--border);
  margin: 2em 0;
}
.prose table {
  width: 100%;
  border-collapse: collapse;
  margin: 1.1em 0;
  font-size: 14px;
  font-family: var(--font-sans);
  line-height: 1.4;
}
.prose th, .prose td {
  border-bottom: 1px solid var(--border);
  border-left: 0;
  border-right: 0;
  border-top: 0;
  padding: 10px 8px 10px 0;
  text-align: left;
  vertical-align: top;
}
.prose th {
  background: transparent;
  font-size: 11px;
  letter-spacing: .08em;
  text-transform: uppercase;
  color: var(--text-faint);
  border-bottom: 1px solid var(--border);
  font-weight: 700;
}
.prose code {
  background: var(--bg-elev-2);
  padding: 1px 5px;
  font-size: 13px;
  border-radius: 4px;
}
.prose pre {
  background: var(--bg-elev);
  border: 1px solid var(--border);
  padding: 12px 14px;
  overflow: auto;
  border-radius: var(--radius);
}
.prose pre code { background: none; padding: 0; }
.prose blockquote {
  margin: 1.2em 0;
  padding: 0 0 0 14px;
  border-left: 3px solid var(--accent);
  color: var(--text-dim);
  font-style: italic;
}

.prose h2[id] { scroll-margin-top: calc(var(--topbar-h) + 12px); }

.rank-toc {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  margin: 0 0 1.8em;
  font-family: var(--font-sans);
  font-size: 13px;
  font-weight: 700;
}
.rank-toc a {
  padding: 6px 12px;
  color: var(--text);
  text-decoration: none;
  background: var(--bg-elev);
  border-radius: var(--radius-pill);
}
.rank-toc a:hover { background: var(--accent); color: var(--accent-ink); }

.rank-meta {
  margin: 0 0 1em;
  padding: 0;
  background: transparent;
  border: 0;
  font-size: 15px;
  font-family: var(--font-sans);
  color: var(--text-dim);
  line-height: 1.5;
}
.rank-meta strong { color: var(--text); font-weight: 800; }
.rank-meta::before {
  content: "";
  display: inline-block;
  width: 8px;
  height: 8px;
  margin-right: 8px;
  border-radius: 50%;
  background: var(--accent);
  vertical-align: middle;
}

.cases {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 12px;
  margin: 1.1em 0 0;
}
.case {
  background: var(--bg-elev);
  border: 0;
  border-top: 0;
  padding: 14px 14px 16px;
  min-width: 0;
  min-height: 0;
  border-radius: var(--radius);
}
.case h3 {
  margin: 0 0 8px;
  font-family: var(--font-sans);
  font-size: 11px;
  font-weight: 800;
  font-style: normal;
  letter-spacing: .08em;
  text-transform: uppercase;
  color: var(--text-faint);
}
.case p {
  margin: 0;
  font-size: 16px;
  font-family: var(--font-serif);
  color: var(--text-dim);
}
.case.best h3 { color: var(--accent-ink); }
.case.best { background: color-mix(in srgb, var(--accent) 42%, var(--bg-elev)); }
.case.worst h3 { color: var(--miss); }
.case.weird h3 { font-style: italic; text-transform: none; letter-spacing: 0; font-family: var(--font-serif); color: var(--text); }

@media (max-width: 700px) {
  .cases { grid-template-columns: 1fr; gap: 10px; }
}

.children {
  margin: 40px 0 0;
  padding: 18px 20px 8px;
  border-top: 0;
  background: var(--bg-elev);
  border-radius: var(--radius);
}
.children h2 {
  margin: 0 0 10px;
  font-family: var(--font-sans);
  font-size: 12px;
  font-weight: 800;
  letter-spacing: .08em;
  text-transform: uppercase;
  color: var(--text-faint);
}
.children ul {
  list-style: none;
  margin: 0;
  padding: 0;
}
.children a {
  display: block;
  padding: 11px 0 11px 18px;
  background: transparent;
  border: 0;
  border-bottom: 1px solid var(--border);
  color: var(--text);
  text-decoration: none;
  font-family: var(--font-display);
  font-size: 17px;
  font-weight: 700;
  letter-spacing: -.01em;
  text-transform: none;
  position: relative;
}
.children a:last-child { border-bottom: 0; }
.children a::before {
  content: "";
  position: absolute;
  left: 0;
  top: 50%;
  width: 8px;
  height: 8px;
  margin-top: -4px;
  border-radius: 50%;
  background: var(--accent);
}
.children a:hover { color: var(--text); background: transparent; }

footer.site {
  max-width: 740px;
  margin: 48px auto 0;
  padding: 18px 32px 56px;
  border-top: 0;
  color: var(--text-faint);
  font-size: 12px;
  font-family: var(--font-sans);
}

@media (max-width: 960px) {
  .sidebar {
    position: fixed;
    top: 0;
    left: 0;
    bottom: 0;
    height: 100dvh;
    width: min(84vw, 300px);
    flex-basis: auto;
    margin-left: 0;
    transform: translateX(-100%);
    box-shadow: var(--shadow);
    transition: transform .2s ease;
  }
  [data-nav="collapsed"] .sidebar { margin-left: 0; }
  [data-drawer="open"] .sidebar { transform: none; }
  [data-drawer="open"] .scrim { display: block; }
  [data-drawer="open"] body { overflow: hidden; }
  .sidebar-dismiss { display: grid; }
  main.page { padding: 24px 20px 10px; }
  footer.site { padding: 18px 20px 56px; }
  h1 { font-size: 32px; }
}

@media (prefers-reduced-motion: reduce) {
  .sidebar, .nav-caret::before { transition: none; }
}
"""

SITE_JS = """\
/* Fantasy Fucks - shared nav + theme behavior. Generated by export_clickup.py. */
(() => {
  const root = document.documentElement;
  const mobile = window.matchMedia("(max-width: 960px)");

  const store = {
    get(key) {
      try { return localStorage.getItem(key); } catch (e) { return null; }
    },
    set(key, value) {
      try { localStorage.setItem(key, value); } catch (e) {}
    },
  };

  function paintTheme(theme) {
    root.dataset.theme = theme;
    const toLight = theme === "dark";
    document.querySelectorAll("[data-theme-toggle]").forEach((btn) => {
      btn.textContent = toLight ? "\\u2600 Light mode" : "\\u263E Dark mode";
      btn.setAttribute("aria-label", `Switch to ${toLight ? "light" : "dark"} mode`);
    });
  }

  function setDrawer(open) {
    if (open) root.setAttribute("data-drawer", "open");
    else root.removeAttribute("data-drawer");
    document.querySelectorAll("[data-nav-toggle]").forEach((btn) => {
      btn.setAttribute("aria-expanded", String(open));
    });
  }

  function setCollapsed(collapsed) {
    if (collapsed) root.setAttribute("data-nav", "collapsed");
    else root.removeAttribute("data-nav");
    store.set("ff-nav-collapsed", collapsed ? "1" : "0");
    document.querySelectorAll("[data-nav-toggle]").forEach((btn) => {
      btn.setAttribute("aria-expanded", String(!collapsed));
    });
  }

  function readSections() {
    try { return JSON.parse(store.get("ff-nav-sections") || "{}"); } catch (e) { return {}; }
  }

  function restoreSections() {
    const saved = readSections();
    document.querySelectorAll(".nav-node.has-kids").forEach((node) => {
      const key = node.dataset.key;
      // The active branch always stays open so the current page is visible.
      if (node.classList.contains("is-branch")) return;
      if (key in saved) node.dataset.open = saved[key] ? "true" : "false";
    });
  }

  function toggleSection(node) {
    const open = node.dataset.open !== "true";
    node.dataset.open = open ? "true" : "false";
    const caret = node.querySelector(":scope > .nav-row > .nav-caret");
    if (caret) caret.setAttribute("aria-expanded", String(open));
    const saved = readSections();
    saved[node.dataset.key] = open;
    store.set("ff-nav-sections", JSON.stringify(saved));
  }

  paintTheme(root.dataset.theme || "light");
  restoreSections();

  document.addEventListener("click", (event) => {
    const themeBtn = event.target.closest("[data-theme-toggle]");
    if (themeBtn) {
      const next = root.dataset.theme === "dark" ? "light" : "dark";
      paintTheme(next);
      store.set("ff-theme", next);
      return;
    }

    const navBtn = event.target.closest("[data-nav-toggle]");
    if (navBtn) {
      if (mobile.matches) setDrawer(root.getAttribute("data-drawer") !== "open");
      else setCollapsed(root.getAttribute("data-nav") !== "collapsed");
      return;
    }

    if (event.target.closest("[data-nav-close]") || event.target.closest(".scrim")) {
      setDrawer(false);
      return;
    }

    const caret = event.target.closest(".nav-caret");
    if (caret) {
      event.preventDefault();
      toggleSection(caret.closest(".nav-node"));
      return;
    }

    if (mobile.matches && event.target.closest(".sidebar-nav a")) setDrawer(false);
  });

  document.addEventListener("keydown", (event) => {
    if (event.key === "Escape" && root.getAttribute("data-drawer") === "open") setDrawer(false);
  });

  mobile.addEventListener("change", () => setDrawer(false));
})();
"""

HEAD_SCRIPT = """\
<script>
  // Apply theme and sidebar state before first paint to avoid a flash.
  (() => {
    const root = document.documentElement;
    let theme = null, collapsed = null;
    try {
      theme = localStorage.getItem("ff-theme");
      collapsed = localStorage.getItem("ff-nav-collapsed");
    } catch (e) {}
    root.dataset.theme = theme || "light";
    if (collapsed === "1") root.setAttribute("data-nav", "collapsed");
  })();
</script>"""


def token() -> str:
    value = os.environ.get("CLICKUP_API_KEY") or os.environ.get("CLICKUP_API_TOKEN")
    if not value:
        sys.exit(
            "Missing ClickUp token. Export CLICKUP_API_KEY in this shell "
            "(you already have it in ~/.zshrc — open a new terminal or run: source ~/.zshrc)."
        )
    return value


def api_get(path: str, params: dict | None = None, retries: int = 4) -> object:
    url = f"{API_BASE}{path}"
    if params:
        url += "?" + urllib.parse.urlencode(params)
    req = urllib.request.Request(
        url,
        headers={
            "Authorization": token(),
            "Accept": "application/json",
        },
    )
    last_error: Exception | None = None
    for attempt in range(retries):
        try:
            with urllib.request.urlopen(req, timeout=60) as resp:
                return json.loads(resp.read().decode("utf-8"))
        except urllib.error.HTTPError as exc:
            body = exc.read().decode("utf-8", errors="replace")
            last_error = exc
            if exc.code in {429, 500, 502, 503, 504} and attempt < retries - 1:
                wait = 1.5 * (attempt + 1)
                print(f"  retry {path} after {exc.code} ({wait:.1f}s)")
                time.sleep(wait)
                continue
            raise RuntimeError(f"ClickUp API {exc.code} for {path}: {body[:500]}") from exc
        except urllib.error.URLError as exc:
            last_error = exc
            if attempt < retries - 1:
                wait = 1.5 * (attempt + 1)
                print(f"  retry {path} after network error ({wait:.1f}s)")
                time.sleep(wait)
                continue
            raise RuntimeError(f"ClickUp API network error for {path}: {exc}") from exc
    raise RuntimeError(f"ClickUp API failed for {path}: {last_error}")


def slugify(name: str) -> str:
    text = name.strip().lower()
    text = re.sub(r"[^a-z0-9]+", "-", text)
    text = re.sub(r"-{2,}", "-", text).strip("-")
    return text or "page"


def ms_to_iso(value: object) -> str | None:
    if not value:
        return None
    try:
        ts = int(value)
    except (TypeError, ValueError):
        return None
    if ts > 10_000_000_000:
        ts /= 1000
    return datetime.fromtimestamp(ts, tz=timezone.utc).strftime("%Y-%m-%d")


def collect_nodes(pages: list) -> list[dict]:
    found: list[dict] = []

    def walk(nodes: list) -> None:
        for node in nodes:
            if not isinstance(node, dict):
                continue
            found.append(node)
            walk(node.get("pages") or [])

    walk(pages)
    return found


def prune(pages: list[dict]) -> list[dict]:
    kept = []
    for page in pages:
        if page.get("deleted") or page.get("archived"):
            continue
        page["pages"] = prune(page.get("pages") or [])
        kept.append(page)
    return kept


def build_tree(pages: list[dict]) -> list[dict]:
    """Return top-level pages, attaching children via `pages` when the API is flat."""
    if any(page.get("pages") for page in pages):
        return pages

    by_id = {page["id"]: page for page in pages if page.get("id")}
    for page in by_id.values():
        page["pages"] = []
    roots: list[dict] = []
    for page in by_id.values():
        parent = page.get("parent_page_id")
        if parent and parent in by_id:
            by_id[parent]["pages"].append(page)
        else:
            roots.append(page)
    return roots


def unique_slug(name: str, used: set[str]) -> str:
    base = slugify(name)
    slug = base
    n = 2
    while slug in used:
        slug = f"{base}-{n}"
        n += 1
    used.add(slug)
    return slug


def assign_paths(roots: list[dict]) -> Path:
    """Give every page a folder. Root index.html is reserved for the keeper page.

    Returns the folder of the Doc's first top-level page, used as the Doc's local home.
    """
    top_slugs: set[str] = {"assets", "index"} | set(TOP_LEVEL_PATHS.values())

    def assign(page: dict, rel: Path, child_slugs: set[str]) -> None:
        page["_rel"] = rel
        page["_file"] = rel / "index.html"
        override = PAGE_TITLES.get(site_key(rel))
        if override:
            page["name"] = override
        next_used: set[str] = set()
        for child in page.get("pages") or []:
            child_slug = unique_slug(child.get("name") or "page", child_slugs)
            assign(child, rel / child_slug, next_used)

    for page in roots:
        name = page.get("name") or "page"
        target = TOP_LEVEL_PATHS.get(slugify(name))
        rel = Path(target) if target else Path(unique_slug(name, top_slugs))
        assign(page, rel, set())

    return roots[0]["_rel"]


def rel_href(from_rel: Path, to_rel: Path) -> str:
    start = Path(".") if from_rel == Path(".") else from_rel
    target = Path(".") if to_rel == Path(".") else to_rel
    href = os.path.relpath(target, start)
    if href == ".":
        return "index.html"
    return href.rstrip("/") + "/"


def page_url_ids(url: str) -> list[str]:
    parsed = urllib.parse.urlparse(url)
    if "clickup.com" not in parsed.netloc:
        return []
    parts = [p for p in parsed.path.split("/") if p]
    return parts


def rewrite_clickup_href(url: str, page: dict, by_id: dict[str, dict], doc_home: Path) -> str:
    if not url or url.startswith("#") or url.startswith("mailto:"):
        return url
    parsed = urllib.parse.urlsplit(url)
    if "clickup.com" not in parsed.netloc:
        return url
    for part in reversed(page_url_ids(url)):
        if part in by_id:
            return rel_href(page["_rel"], by_id[part]["_rel"])
    if DOC_ID in url:
        return rel_href(page["_rel"], doc_home)
    return url


def download_image(url: str, assets: Path, cache: dict[str, str]) -> str | None:
    if url in cache:
        return cache[url]
    if url.startswith("data:") or url.startswith("#"):
        return None
    parsed = urllib.parse.urlsplit(url)
    if parsed.scheme not in {"http", "https"}:
        return None
    ext = Path(parsed.path).suffix.lower()
    if ext not in {".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg", ".avif"}:
        ext = ".png"
    digest = hashlib.sha256(url.encode()).hexdigest()[:16]
    filename = f"{digest}{ext}"
    dest = assets / filename
    if not dest.exists():
        headers = {"User-Agent": "fantasy-fucks-clickup-export/1.0"}
        if CLICKUP_HOST_RE.match(url) or "clickup.com" in parsed.netloc:
            headers["Authorization"] = token()
        req = urllib.request.Request(url, headers=headers)
        try:
            with urllib.request.urlopen(req, timeout=60) as resp:
                dest.write_bytes(resp.read())
        except (urllib.error.URLError, urllib.error.HTTPError) as exc:
            print(f"  skip image {url}: {exc}")
            return None
    cache[url] = filename
    return filename


def asset_href(page: dict, filename: str) -> str:
    assets_rel = Path("assets") / filename
    start = Path(".") if page["_rel"] == Path(".") else page["_rel"]
    return os.path.relpath(assets_rel, start)


def localize_images(text: str, page: dict, assets: Path, cache: dict[str, str]) -> str:
    def replace_md(match: re.Match) -> str:
        alt, url = match.group(1), match.group(2)
        name = download_image(url, assets, cache)
        if not name:
            return match.group(0)
        return f"![{alt}]({asset_href(page, name)})"

    def replace_html(match: re.Match) -> str:
        url = match.group(2)
        name = download_image(url, assets, cache)
        if not name:
            return match.group(0)
        return f"{match.group(1)}{asset_href(page, name)}{match.group(3)}"

    text = IMG_MD_RE.sub(replace_md, text)
    text = IMG_HTML_RE.sub(replace_html, text)
    return text


def rewrite_markdown_links(text: str, page: dict, by_id: dict[str, dict], doc_home: Path) -> str:
    def repl(match: re.Match) -> str:
        label, url = match.group(1), match.group(2)
        return f"[{label}]({rewrite_clickup_href(url, page, by_id, doc_home)})"

    return MD_LINK_RE.sub(repl, text)


def md_to_html(text: str) -> str:
    return markdown.markdown(
        text or "",
        extensions=["extra", "sane_lists", "smarty"],
        output_format="html5",
    )


def rewrite_html_hrefs(html: str, page: dict, by_id: dict[str, dict], doc_home: Path) -> str:
    def repl(match: re.Match) -> str:
        return (
            f"{match.group(1)}"
            f"{rewrite_clickup_href(match.group(2), page, by_id, doc_home)}"
            f"{match.group(3)}"
        )

    return HREF_RE.sub(repl, html)


def css_href(page: dict) -> str:
    start = Path(".") if page["_rel"] == Path(".") else page["_rel"]
    return os.path.relpath("site.css", start)


def href_from(rel: Path, target: str) -> str:
    start = Path(".") if rel == Path(".") else rel
    href = os.path.relpath(target, start).replace("\\", "/")
    if href == ".":
        return "index.html" if target.endswith(".html") else "./"
    if target.endswith("/") and not href.endswith(("/", ".html")):
        href += "/"
    return href


def site_key(rel: Path) -> str:
    """Root-relative key used to match a page against the nav tree."""
    if rel in (Path("."), Path("")):
        return "index.html"
    return rel.as_posix() + "/"


def nav_items(tree: list[dict], rel: Path, current: str) -> str:
    def contains_current(node: dict) -> bool:
        if node["href"] == current:
            return True
        return any(contains_current(kid) for kid in node.get("children") or [])

    def render(nodes: list[dict], depth: int) -> str:
        out = []
        for node in nodes:
            kids = node.get("children") or []
            active = node["href"] == current
            branch = contains_current(node)
            classes = ["nav-node"]
            if kids:
                classes.append("has-kids")
            if branch:
                classes.append("is-branch")
            label = esc(node["label"])
            link = (
                f'<a class="nav-link" href="{href_from(rel, node["href"])}" title="{label}"'
                + (' aria-current="page"' if active else "")
                + f">{label}</a>"
            )
            if not kids:
                out.append(f'<li class="{" ".join(classes)}">{link}</li>')
                continue
            open_state = "true" if branch else "false"
            caret = (
                f'<button class="nav-caret" type="button" aria-expanded="{open_state}"'
                f' aria-label="Toggle {esc(node["label"])}"></button>'
            )
            out.append(
                f'<li class="{" ".join(classes)}" data-key="{esc(node["href"])}" data-open="{open_state}">'
                f'<div class="nav-row">{link}{caret}</div>'
                f'<ul class="nav-list nav-sub">{render(kids, depth + 1)}</ul>'
                "</li>"
            )
        return "".join(out)

    return render(tree, 0)


def site_chrome(
    rel: Path,
    tree: list[dict],
    site_name: str = "Fantasy Fucks",
    title: str = "",
    current: str | None = None,
) -> str:
    """Sidebar + topbar markup shared by every page."""
    current = current or site_key(rel)
    home = href_from(rel, "index.html")
    initials = "".join(word[0] for word in site_name.split()[:2]).upper() or "FF"
    return f"""<aside class="sidebar" id="sidebar" aria-label="Site navigation">
  <div class="sidebar-top">
    <a class="brand" href="{home}">
      <span class="brand-mark">{esc(initials)}</span>
      <span class="brand-name">{esc(site_name)}</span>
    </a>
    <button class="icon-btn sidebar-dismiss" type="button" data-nav-close aria-label="Close navigation">&#10005;</button>
  </div>
  <nav class="sidebar-nav">
    <ul class="nav-list">{nav_items(tree, rel, current)}</ul>
  </nav>
  <div class="sidebar-bottom">
    <button class="theme-btn" type="button" data-theme-toggle>&#9790; Dark mode</button>
  </div>
</aside>
<div class="content">
  <header class="topbar">
    <button class="icon-btn" type="button" data-nav-toggle aria-controls="sidebar" aria-expanded="true" aria-label="Toggle navigation">&#9776;</button>
    <span class="topbar-title">{esc(title or site_name)}</span>
  </header>"""


def flat_labels(tree: list[dict], out: dict[str, str] | None = None) -> dict[str, str]:
    out = {} if out is None else out
    for node in tree:
        out[node["href"]] = node["label"]
        flat_labels(node.get("children") or [], out)
    return out


def render_page(page: dict, by_id: dict[str, dict], site_name: str, tree: list[dict]) -> str:
    # Breadcrumbs follow the folder layout, so re-homed pages read the way the nav shows them.
    labels = flat_labels(tree)
    parts = page["_rel"].parts
    crumbs = []
    for depth in range(1, len(parts)):
        href = "/".join(parts[:depth]) + "/"
        if href in labels:
            target = href_from(page["_rel"], href)
            crumbs.append(f'<a href="{target}">{esc(labels[href])}</a>')
    crumbs.append(esc(page.get("name") or "Page"))
    crumb_html = " / ".join(crumbs)

    children = page.get("pages") or []
    child_html = ""
    if children:
        items = "".join(
            f'<li><a href="{rel_href(page["_rel"], child["_rel"])}">{esc(child.get("name") or "Page")}</a></li>'
            for child in children
        )
        child_html = f'<nav class="children"><h2>Pages</h2><ul>{items}</ul></nav>'

    updated = ms_to_iso(page.get("date_updated") or page.get("date_edited"))
    subtitle = page.get("sub_title") or ""
    meta = f'<p class="meta">Updated {esc(updated)}</p>' if updated else ""
    subtitle_html = f'<p class="subtitle">{esc(subtitle)}</p>' if subtitle else ""

    rel = page["_rel"]
    name = page.get("name") or "Untitled"
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="dark light">
<title>{esc(name)} — {esc(site_name)}</title>
<link rel="stylesheet" href="{css_href(page)}">
{HEAD_SCRIPT}
</head>
<body>
<!-- clickup-export:{page.get("id", "")} -->
<a class="skip-link" href="#main">Skip to content</a>
<div class="shell">
{site_chrome(rel, tree, site_name, name)}
<main class="page" id="main">
  <p class="crumbs">{crumb_html}</p>
  <h1>{esc(name)}</h1>
  {subtitle_html}
  {meta}
  <article class="prose">
{page.get("_html") or ""}
  </article>
  {child_html}
</main>
<footer class="site">Exported from ClickUp Doc {esc(DOC_ID)}.</footer>
</div>
</div>
<div class="scrim"></div>
<script src="{href_from(rel, "site.js")}"></script>
</body>
</html>
"""


def esc(value: object) -> str:
    return (
        str(value or "")
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def fetch_pages() -> list[dict]:
    payload = api_get(
        f"/workspaces/{WORKSPACE_ID}/docs/{DOC_ID}/pages",
        {"max_page_depth": "-1", "content_format": "text/md"},
    )
    if isinstance(payload, dict):
        pages = payload.get("pages") or payload.get("data") or []
        if isinstance(pages, dict):
            pages = [pages]
    elif isinstance(payload, list):
        pages = payload
    else:
        sys.exit(f"Unexpected pages payload: {type(payload)}")

    nodes = collect_nodes(pages)
    for node in nodes:
        if node.get("deleted") or node.get("archived"):
            continue
        if node.get("content"):
            continue
        time.sleep(0.15)
        detail = api_get(
            f"/workspaces/{WORKSPACE_ID}/docs/{DOC_ID}/pages/{node['id']}",
            {"content_format": "text/md"},
        )
        if isinstance(detail, dict) and detail.get("content"):
            node["content"] = detail["content"]
            node.setdefault("sub_title", detail.get("sub_title"))
            node.setdefault("date_updated", detail.get("date_updated"))
            if detail.get("cover"):
                node["cover"] = detail["cover"]
    return prune(pages)


NAV_FILE = "nav.json"
CHROME_MARKER = "<!-- site-chrome -->"
CHILDREN_RE = re.compile(r'<nav class="children">.*?</nav>', re.S)
CHILD_LINK_RE = re.compile(r'<li><a href="([^"]+)">(.*?)</a></li>', re.S)
H1_RE = re.compile(r"<h1[^>]*>(.*?)</h1>", re.S)
OLD_HEADER_RE = re.compile(r'<header class="site">.*?</header>\s*', re.S)
CHROME_RE = re.compile(r'<aside class="sidebar".*?</header>', re.S)


def nav_from_pages(roots: list[dict]) -> list[dict]:
    """Nav tree for the sidebar, nested by output folder rather than ClickUp parentage."""
    nodes = [
        {
            "label": page.get("name") or "Page",
            "href": site_key(page["_rel"]),
            "children": [],
        }
        for page in collect_nodes(roots)
    ]
    by_href = {node["href"]: node for node in nodes}

    tree: list[dict] = []
    for node in nodes:
        parent = None
        for href, candidate in by_href.items():
            if candidate is node or not href.endswith("/"):
                continue
            if node["href"].startswith(href) and (parent is None or len(href) > len(parent["href"])):
                parent = candidate
        (parent["children"] if parent else tree).append(node)

    extra = [
        {"label": "2026 Draft and Keeper Info", "href": "index.html", "children": []},
        {"label": "2026 Keepers", "href": "2026-keepers/", "children": []},
    ]
    skip = {item["href"] for item in extra}
    tree = [node for node in tree if node["href"] not in skip]
    rules = next((node for node in tree if node["href"] == "rules/"), None)
    if rules is None:
        rules = {"label": "Rules", "href": "rules/", "children": []}
        tree.append(rules)
    have = {child["href"] for child in rules["children"]}
    for item in reversed(extra):
        if item["href"] not in have:
            rules["children"].insert(0, item)

    def reorder(nodes: list[dict], parent_href: str) -> None:
        pinned = NAV_FIRST.get(parent_href, ())
        nodes.sort(key=lambda n: pinned.index(n["href"]) if n["href"] in pinned else len(pinned))
        for node in nodes:
            reorder(node["children"], node["href"])

    for node in tree:
        reorder(node["children"], node["href"])

    order = {target: i for i, (_, target) in enumerate(SITE_NAV)}
    tree.sort(key=lambda n: order.get(n["href"], len(order)))

    for item in tree:
        for label, target in SITE_NAV:
            if item["href"] == target:
                item["label"] = label
    return tree


def nav_from_disk(root: Path) -> list[dict]:
    """Rebuild the nav tree from exported HTML, using each page's child list for ordering."""

    def read(rel: Path) -> tuple[str, list[tuple[str, str]]]:
        path = root / rel / "index.html" if rel != Path(".") else root / "index.html"
        text = path.read_text(encoding="utf-8", errors="replace")
        heading = H1_RE.search(text)
        label = html_lib.unescape(heading.group(1).strip()) if heading else rel.name
        block = CHILDREN_RE.search(text)
        kids = []
        if block:
            for href, raw in CHILD_LINK_RE.findall(block.group(0)):
                kids.append((href.strip("/"), html_lib.unescape(raw.strip())))
        return label, kids

    def node(rel: Path) -> dict:
        label, kids = read(rel)
        return {
            "label": label,
            "href": site_key(rel),
            "children": [node(rel / slug) for slug, _ in kids],
        }

    tree = []
    for label, target in SITE_NAV:
        if target.endswith(".html"):
            tree.append({"label": label, "href": target, "children": []})
            continue
        rel = Path(target.rstrip("/"))
        if (root / rel / "index.html").exists():
            item = node(rel)
            item["label"] = label
            tree.append(item)
    return tree


def load_nav(root: Path) -> list[dict]:
    path = root / NAV_FILE
    if path.exists():
        return json.loads(path.read_text(encoding="utf-8"))
    tree = nav_from_disk(root)
    path.write_text(json.dumps(tree, indent=2), encoding="utf-8")
    print(f"Built {NAV_FILE} from exported pages")
    return tree


def write_shared_assets(root: Path, tree: list[dict]) -> None:
    (root / "site.css").write_text(SITE_CSS, encoding="utf-8")
    (root / "site.js").write_text(SITE_JS, encoding="utf-8")
    (root / NAV_FILE).write_text(json.dumps(tree, indent=2), encoding="utf-8")


def nav_label(tree: list[dict], href: str) -> str | None:
    for node in tree:
        if node["href"] == href:
            return node["label"]
        found = nav_label(node.get("children") or [], href)
        if found:
            return found
    return None


def patch_chrome(root: Path, tree: list[dict], site_name: str = "Fantasy Fucks") -> None:
    """Swap the sidebar/topbar on already-exported pages without re-fetching ClickUp."""
    targets: list[tuple[Path, str]] = []
    for path in sorted(root.rglob("index.html")):
        if any(part.startswith(".") for part in path.relative_to(root).parts):
            continue
        targets.append((path, site_key(path.parent.relative_to(root))))

    updated = 0
    for path, current in targets:
        text = path.read_text(encoding="utf-8")
        is_export = "clickup-export:" in text
        if not is_export and CHROME_MARKER not in text and not CHROME_RE.search(text):
            continue
        rel = path.parent.relative_to(root)
        heading = H1_RE.search(text)
        heading_text = html_lib.unescape(heading.group(1).strip()) if heading else ""
        title = (heading_text if is_export else "") or nav_label(tree, current) or site_name
        chrome = site_chrome(rel, tree, site_name, title, current)

        if CHROME_RE.search(text):
            patched = CHROME_RE.sub(lambda _: chrome, text, count=1)
        elif CHROME_MARKER in text:
            patched = text.replace(CHROME_MARKER, chrome, 1)
        elif OLD_HEADER_RE.search(text):
            patched = OLD_HEADER_RE.sub(
                lambda _: f'<a class="skip-link" href="#main">Skip to content</a>\n'
                f'<div class="shell">\n{chrome}\n',
                text,
                count=1,
            )
            patched = patched.replace("<main>", '<main class="page" id="main">', 1)
            patched = patched.replace(
                "</main>\n<footer class=\"site\">",
                '</main>\n<footer class="site">',
                1,
            )
            patched = patched.replace(
                "</footer>\n</body>",
                f'</footer>\n</div>\n</div>\n<div class="scrim"></div>\n'
                f'<script src="{href_from(rel, "site.js")}"></script>\n</body>',
                1,
            )
            patched = patched.replace(
                '<meta name="viewport" content="width=device-width, initial-scale=1">',
                '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
                '<meta name="color-scheme" content="dark light">',
                1,
            )
            patched = patched.replace("</head>", f"{HEAD_SCRIPT}\n</head>", 1)
        else:
            continue

        if patched != text:
            path.write_text(patched, encoding="utf-8")
            updated += 1
    print(f"Updated chrome on {updated} page(s)")


def write_site(root: Path, dry_run: bool) -> None:
    print(f"Fetching ClickUp Doc {DOC_ID}…")
    site_name = "Fantasy Fucks"
    try:
        doc = api_get(f"/workspaces/{WORKSPACE_ID}/docs/{DOC_ID}")
        if isinstance(doc, dict) and doc.get("name"):
            site_name = doc["name"]
    except RuntimeError as exc:
        print(f"  skipping doc metadata ({exc})")
    roots = build_tree(fetch_pages())
    if not roots:
        sys.exit("No pages returned for this Doc.")
    doc_home = assign_paths(roots)
    nodes = collect_nodes(roots)
    by_id = {page["id"]: page for page in nodes if page.get("id")}

    print(f"{len(nodes)} page(s):")
    for page in nodes:
        print(f"  {page['_file']}  ←  {page.get('name')}")

    if dry_run:
        return

    tree = nav_from_pages(roots)
    assets = root / "assets"
    assets.mkdir(exist_ok=True)
    write_shared_assets(root, tree)
    cache: dict[str, str] = {}

    for page in nodes:
        cover = (page.get("cover") or {}).get("image_url")
        body = page.get("content") or ""
        if cover:
            name = download_image(cover, assets, cache)
            if name:
                body = f"![cover]({asset_href(page, name)})\n\n" + body
        body = localize_images(body, page, assets, cache)
        body = rewrite_markdown_links(body, page, by_id, doc_home)
        html = rewrite_html_hrefs(md_to_html(body), page, by_id, doc_home)
        html = localize_images(html, page, assets, cache)
        page["_html"] = html

        dest = root / page["_file"]
        if dest.relative_to(root).as_posix() in PROTECTED:
            print(f"  skip protected {dest}")
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(render_page(page, by_id, site_name, tree), encoding="utf-8")

    print(f"Wrote HTML under {root}")
    # The keeper homepage isn't a ClickUp export, so refresh its chrome from the same tree.
    patch_chrome(root, tree, site_name)


def main() -> None:
    parser = argparse.ArgumentParser(description="Export a ClickUp Doc to local HTML.")
    parser.add_argument(
        "--out",
        default=str(Path(__file__).resolve().parent),
        help="Site root (default: this folder)",
    )
    parser.add_argument("--dry-run", action="store_true", help="Print the page tree without writing files")
    parser.add_argument(
        "--patch-nav",
        action="store_true",
        help="Rebuild styles and sidebar on already-exported HTML without calling ClickUp",
    )
    args = parser.parse_args()
    root = Path(args.out).resolve()
    if args.patch_nav:
        tree = load_nav(root)
        write_shared_assets(root, tree)
        patch_chrome(root, tree)
        return
    write_site(root, args.dry_run)


if __name__ == "__main__":
    main()
