/* Fantasy Fucks - shared nav + theme behavior. Generated by export_clickup.py. */
(() => {
  const root = document.documentElement;
  const mobile = window.matchMedia("(max-width: 960px)");

  const store = {
    get(key) {
      try { return localStorage.getItem(key); } catch (e) { return null; }
    },
    set(key, value) {
      try { localStorage.setItem(key, value); } catch (e) {}
    },
  };

  function paintTheme(theme) {
    root.dataset.theme = theme;
    const toLight = theme === "dark";
    document.querySelectorAll("[data-theme-toggle]").forEach((btn) => {
      btn.textContent = toLight ? "\u2600 Light mode" : "\u263E Dark mode";
      btn.setAttribute("aria-label", `Switch to ${toLight ? "light" : "dark"} mode`);
    });
  }

  function setDrawer(open) {
    if (open) root.setAttribute("data-drawer", "open");
    else root.removeAttribute("data-drawer");
    document.querySelectorAll("[data-nav-toggle]").forEach((btn) => {
      btn.setAttribute("aria-expanded", String(open));
    });
  }

  function setCollapsed(collapsed) {
    if (collapsed) root.setAttribute("data-nav", "collapsed");
    else root.removeAttribute("data-nav");
    store.set("ff-nav-collapsed", collapsed ? "1" : "0");
    document.querySelectorAll("[data-nav-toggle]").forEach((btn) => {
      btn.setAttribute("aria-expanded", String(!collapsed));
    });
  }

  function readSections() {
    try { return JSON.parse(store.get("ff-nav-sections") || "{}"); } catch (e) { return {}; }
  }

  function restoreSections() {
    const saved = readSections();
    document.querySelectorAll(".nav-node.has-kids").forEach((node) => {
      const key = node.dataset.key;
      // The active branch always stays open so the current page is visible.
      if (node.classList.contains("is-branch")) return;
      if (key in saved) node.dataset.open = saved[key] ? "true" : "false";
    });
  }

  function toggleSection(node) {
    const open = node.dataset.open !== "true";
    node.dataset.open = open ? "true" : "false";
    const caret = node.querySelector(":scope > .nav-row > .nav-caret");
    if (caret) caret.setAttribute("aria-expanded", String(open));
    const saved = readSections();
    saved[node.dataset.key] = open;
    store.set("ff-nav-sections", JSON.stringify(saved));
  }

  paintTheme(root.dataset.theme || "light");
  restoreSections();

  document.addEventListener("click", (event) => {
    const themeBtn = event.target.closest("[data-theme-toggle]");
    if (themeBtn) {
      const next = root.dataset.theme === "dark" ? "light" : "dark";
      paintTheme(next);
      store.set("ff-theme", next);
      return;
    }

    const navBtn = event.target.closest("[data-nav-toggle]");
    if (navBtn) {
      if (mobile.matches) setDrawer(root.getAttribute("data-drawer") !== "open");
      else setCollapsed(root.getAttribute("data-nav") !== "collapsed");
      return;
    }

    if (event.target.closest("[data-nav-close]") || event.target.closest(".scrim")) {
      setDrawer(false);
      return;
    }

    const caret = event.target.closest(".nav-caret");
    if (caret) {
      event.preventDefault();
      toggleSection(caret.closest(".nav-node"));
      return;
    }

    if (mobile.matches && event.target.closest(".sidebar-nav a")) setDrawer(false);
  });

  document.addEventListener("keydown", (event) => {
    if (event.key === "Escape" && root.getAttribute("data-drawer") === "open") setDrawer(false);
  });

  mobile.addEventListener("change", () => setDrawer(false));
})();
